# Generated by Django 5.2.17 on 2026-08-13 03:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tên nhóm')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Nhóm bài viết',
                'verbose_name_plural': 'Nhóm bài viết',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='Nội dung HTML')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Xuất bản')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trang tĩnh',
                'verbose_name_plural': 'Trang tĩnh',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Tóm tắt')),
                ('body', models.TextField(verbose_name='Nội dung HTML')),
                ('cover', models.ImageField(blank=True, upload_to='articles/', verbose_name='Ảnh bìa')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Xuất bản')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='content.articlecategory', verbose_name='Nhóm')),
            ],
            options={
                'verbose_name': 'Bài viết SEO',
                'verbose_name_plural': 'Bài viết SEO',
                'ordering': ['-published_at'],
            },
        ),
    ]
