# Generated by Django 5.2.17 on 2026-08-13 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(default='Ban biên tập Keno', max_length=120, verbose_name='Tác giả'),
        ),
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.CharField(blank=True, help_text='Để trống = URL bài viết. Chỉ điền khi cần trỏ sang URL khác.', max_length=300, verbose_name='Canonical (tùy chọn)'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_alt',
            field=models.CharField(blank=True, max_length=160, verbose_name='Alt ảnh bìa'),
        ),
        migrations.AddField(
            model_name='article',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=80, verbose_name='Từ khóa chính'),
        ),
        migrations.AddField(
            model_name='article',
            name='key_takeaways',
            field=models.TextField(blank=True, help_text='Hiển thị cho độc giả và LLM ngay dưới intro.', verbose_name='Ý chính (mỗi dòng một ý)'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='articles/og/', verbose_name='Ảnh Open Graph'),
        ),
        migrations.AddField(
            model_name='article',
            name='robots_noindex',
            field=models.BooleanField(default=False, help_text='Bật để không đưa vào sitemap / Google. Bản nháp AI nên để noindex.', verbose_name='noindex'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='canonical_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='Canonical (tùy chọn)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='Tóm tắt'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='pages/og/', verbose_name='Ảnh OG'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='robots_noindex',
            field=models.BooleanField(default=False, verbose_name='noindex'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Đoạn mở đầu cho AI search và meta. 1–2 câu trả lời trực tiếp.', verbose_name='Tóm tắt / excerpt LLM'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Khuyến nghị ≤ 155 ký tự.', max_length=160, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Khuyến nghị ≤ 60 ký tự.', max_length=70, verbose_name='SEO title'),
        ),
        migrations.CreateModel(
            name='ArticleFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Câu hỏi')),
                ('answer', models.TextField(verbose_name='Câu trả lời')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='content.article', verbose_name='Bài viết')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
