# Generated by Django 5.2.17 on 2026-08-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_author_name_article_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='canonical_url',
            field=models.CharField(blank=True, help_text='Để trống nếu dùng URL bài.', max_length=300, verbose_name='Canonical (tùy chọn)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='1–2 câu tóm tắt.', verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='key_takeaways',
            field=models.TextField(blank=True, help_text='Mỗi dòng một ý.', verbose_name='Ý chính (mỗi dòng một ý)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='robots_noindex',
            field=models.BooleanField(default=False, help_text='Ẩn khỏi sitemap và Google.', verbose_name='noindex'),
        ),
    ]
