# Generated by Django 5.2.17 on 2026-08-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Tiêu đề')),
                ('subtitle', models.CharField(blank=True, max_length=240, verbose_name='Phụ đề')),
                ('image', models.ImageField(blank=True, upload_to='banners/', verbose_name='Hình banner')),
                ('link_url', models.CharField(blank=True, max_length=300, verbose_name='Đường dẫn')),
                ('placement', models.CharField(choices=[('home', 'Trang chủ'), ('community', 'Cộng đồng'), ('pos', 'Điểm bán')], default='home', max_length=32, verbose_name='Vị trí')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiện')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Keno', max_length=120, verbose_name='Tên website')),
                ('tagline', models.CharField(default='Tra cứu kết quả · Cộng đồng · Điểm bán gần bạn', max_length=200, verbose_name='Khẩu hiệu')),
                ('facebook_group_url', models.URLField(blank=True, default='https://www.facebook.com/groups/', verbose_name='Link nhóm Facebook')),
                ('facebook_group_name', models.CharField(default='Cộng đồng người chơi Keno', max_length=160, verbose_name='Tên nhóm cộng đồng')),
                ('support_note', models.TextField(default='Website này phục vụ tra cứu, tìm hiểu sản phẩm và kết nối điểm bán. Keno chỉ được phân phối tại các điểm bán chính thức. Không mua vé trực tuyến trên website này.', verbose_name='Ghi chú trách nhiệm')),
                ('ga4_measurement_id', models.CharField(blank=True, max_length=32, verbose_name='GA4 Measurement ID')),
                ('gtm_container_id', models.CharField(blank=True, max_length=32, verbose_name='GTM Container ID')),
                ('community_cta_label', models.CharField(default='Tham gia cộng đồng', max_length=80, verbose_name='Nhãn CTA cộng đồng')),
                ('pos_cta_label', models.CharField(default='Tìm điểm bán gần bạn', max_length=80, verbose_name='Nhãn CTA điểm bán')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cài đặt website',
                'verbose_name_plural': 'Cài đặt website',
            },
        ),
    ]
