# Generated by Django 5.2.17 on 2026-08-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_social_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_moderation_roles',
            field=models.TextField(blank=True, default='', help_text='Vai trò trên Page (Admin/Editor/Moderator). CMS không thay Facebook Roles.', verbose_name='Ghi chú kiểm duyệt Fanpage'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_page_access_token',
            field=models.CharField(blank=True, default='', help_text='Bí mật. Không hiện đầy đủ trong CMS. Có thể để trong .env.', max_length=512, verbose_name='Page Access Token'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_page_id',
            field=models.CharField(blank=True, default='', help_text='ID số của Page, dùng Graph API đồng bộ bài viết.', max_length=64, verbose_name='Facebook Page ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='o2o_commission_base_vnd',
            field=models.PositiveIntegerField(default=10000, help_text='Dùng khi tính hoa hồng theo %.', verbose_name='Giá trị vé giả định (VND)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='o2o_commission_rate',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Cố định: số VND mỗi lượt quét. Phần trăm: ví dụ 5.00 = 5%.', max_digits=12, verbose_name='Mức hoa hồng'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='o2o_commission_type',
            field=models.CharField(choices=[('fixed', 'Cố định (VND / lượt quét)'), ('percent', 'Phần trăm trên giá trị vé giả định')], default='fixed', max_length=16, verbose_name='Cách tính hoa hồng O2O'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='wallet_vnd_per_point',
            field=models.PositiveIntegerField(default=1000, help_text='Tỷ lệ quy đổi ví chủ điểm bán (mô phỏng).', verbose_name='1 điểm thưởng = VND'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_app_id',
            field=models.CharField(blank=True, default='', help_text='Cần cho Page Plugin và Comments SDK.', max_length=64, verbose_name='Facebook App ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_comments_url',
            field=models.URLField(blank=True, default='', help_text='Để trống thì dùng URL Fanpage.', verbose_name='URL bình luận Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_page_url',
            field=models.URLField(blank=True, default='', help_text='URL Fanpage — nhúng Page Plugin (timeline).', verbose_name='Link Facebook Page'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='support_note',
            field=models.TextField(default='Keno chỉ mua tại điểm bán chính thức.', verbose_name='Ghi chú trách nhiệm'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='zalo_group_url',
            field=models.URLField(blank=True, default='', help_text='Nhóm Zalo điểm bán.', verbose_name='Link nhóm Zalo'),
        ),
    ]
