# Generated by Django 5.2.17 on 2026-08-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Mã')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Hết hạn')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Đã quét tại POS')),
                ('pos_name', models.CharField(blank=True, max_length=160, verbose_name='Điểm bán quét mã')),
                ('session_key', models.CharField(blank=True, max_length=64, verbose_name='Phiên web')),
            ],
            options={
                'verbose_name': 'Mã trải nghiệm O2O',
                'verbose_name_plural': 'Mã trải nghiệm O2O',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PosLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Tên điểm bán')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('district', models.CharField(blank=True, max_length=80, verbose_name='Quận/Huyện')),
                ('city', models.CharField(db_index=True, max_length=80, verbose_name='Tỉnh/Thành')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kinh độ')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Điện thoại')),
                ('opening_hours', models.CharField(blank=True, default='06:00 – 22:00', max_length=120, verbose_name='Giờ mở cửa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Điểm bán Keno',
                'verbose_name_plural': 'Điểm bán Keno',
                'ordering': ['city', 'name'],
            },
        ),
    ]
