# Generated by Django 5.2.17 on 2026-08-13 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencecode',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_codes', to='locations.poslocation', verbose_name='Điểm bán'),
        ),
        migrations.AddField(
            model_name='poslocation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pos_locations', to=settings.AUTH_USER_MODEL, verbose_name='Chủ điểm bán'),
        ),
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_vnd', models.PositiveIntegerField(default=0, verbose_name='Hoa hồng (VND)')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Điểm thưởng')),
                ('status', models.CharField(choices=[('pending', 'Chờ ghi nhận'), ('available', 'Khả dụng'), ('paid', 'Đã quyết toán (mô phỏng)')], db_index=True, default='available', max_length=16, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ghi nhận lúc')),
                ('experience_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='locations.experiencecode', verbose_name='Mã O2O')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_commissions', to=settings.AUTH_USER_MODEL, verbose_name='Chủ điểm bán')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='locations.poslocation', verbose_name='Điểm bán')),
            ],
            options={
                'verbose_name': 'Hoa hồng O2O',
                'verbose_name_plural': 'Hoa hồng O2O',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.PositiveIntegerField(default=0, verbose_name='Điểm hiện có')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_wallet', to=settings.AUTH_USER_MODEL, verbose_name='Chủ điểm bán')),
            ],
            options={
                'verbose_name': 'Ví chủ điểm bán',
                'verbose_name_plural': 'Ví chủ điểm bán',
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(verbose_name='Điểm quy đổi')),
                ('amount_vnd', models.PositiveIntegerField(verbose_name='Số tiền (VND)')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt (mô phỏng)'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=16, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gửi lúc')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Duyệt lúc')),
                ('staff_note', models.CharField(blank=True, max_length=200, verbose_name='Ghi chú CMS')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL, verbose_name='Chủ điểm bán')),
            ],
            options={
                'verbose_name': 'Yêu cầu quy đổi',
                'verbose_name_plural': 'Yêu cầu quy đổi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('earn', 'Hoa hồng O2O'), ('payout', 'Yêu cầu quy đổi'), ('refund', 'Hoàn điểm')], default='earn', max_length=16, verbose_name='Loại')),
                ('points', models.IntegerField(default=0, verbose_name='Điểm (+/−)')),
                ('amount_vnd', models.IntegerField(default=0, verbose_name='VND tương đương')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entries', to='locations.commissionledger', verbose_name='Hoa hồng')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entries', to='locations.payoutrequest', verbose_name='Yêu cầu quy đổi')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='locations.ownerwallet', verbose_name='Ví')),
            ],
            options={
                'verbose_name': 'Biến động ví',
                'verbose_name_plural': 'Biến động ví',
                'ordering': ['-created_at'],
            },
        ),
    ]
