# Generated by Django 5.2.17 on 2026-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_fanpage_and_pos_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=16, verbose_name='Trạng thái'),
        ),
    ]
