"""Sample market-content metadata for the research tool (not scraped full text)."""

SAMPLE_MARKET = [
    {
        "url": "https://example.com/mau/keno-la-gi",
        "product_hint": "keno",
        "title": "Keno là gì? Hướng dẫn người mới (mẫu thị trường)",
        "meta_description": "Giải thích Keno, tần suất 8 phút, chọn 1–10 số — bài mẫu để so gap nội dung.",
        "canonical": "https://example.com/mau/keno-la-gi",
        "headings": [
            {"tag": "h1", "text": "Keno là gì?"},
            {"tag": "h2", "text": "Cách chọn số"},
            {"tag": "h2", "text": "Lớn nhỏ chẵn lẻ"},
            {"tag": "h2", "text": "Mua vé ở đâu"},
        ],
        "outline": "H1: Keno là gì?\nH2: Cách chọn số\nH2: Lớn nhỏ chẵn lẻ\nH2: Mua vé ở đâu",
        "excerpt": "Bài mẫu: Keno là xổ số nhanh, mở thưởng liên tục. Người mới cần hiểu cách chọn số và nơi mua vé.",
        "word_count": 980,
        "keyword_hints": "keno là gì, cách chơi keno, điểm bán",
        "schema_types": "Article, FAQPage",
        "published_hint": "2026-01-15",
        "status": "sample",
    },
    {
        "url": "https://example.com/mau/ket-qua-keno-hom-nay",
        "product_hint": "keno",
        "title": "Kết quả Keno hôm nay theo từng kỳ",
        "meta_description": "Trang kết quả theo kỳ — đối thủ thường tối ưu từ khóa kết quả + hôm nay.",
        "canonical": "https://example.com/mau/ket-qua-keno-hom-nay",
        "headings": [
            {"tag": "h1", "text": "Kết quả Keno hôm nay"},
            {"tag": "h2", "text": "Kỳ mới nhất"},
            {"tag": "h2", "text": "Lịch sử trong ngày"},
        ],
        "outline": "H1: Kết quả Keno hôm nay\nH2: Kỳ mới nhất\nH2: Lịch sử trong ngày",
        "excerpt": "Bài mẫu tập trung vào truy vấn 'kết quả keno hôm nay' và bảng kỳ quay.",
        "word_count": 620,
        "keyword_hints": "kết quả keno, keno hôm nay",
        "schema_types": "WebPage",
        "published_hint": "2026-08-01",
        "status": "sample",
    },
    {
        "url": "https://example.com/mau/mega-645-la-gi",
        "product_hint": "mega645",
        "title": "Mega 6/45 là gì — khác Keno thế nào?",
        "meta_description": "Nhiều trang xổ số so sánh Mega 6/45 với Keno; đây là khoảng trống nội dung mẫu.",
        "canonical": "https://example.com/mau/mega-645-la-gi",
        "headings": [
            {"tag": "h1", "text": "Mega 6/45 là gì?"},
            {"tag": "h2", "text": "Tần suất mở thưởng"},
            {"tag": "h2", "text": "So với Keno"},
        ],
        "outline": "H1: Mega 6/45 là gì?\nH2: Tần suất mở thưởng\nH2: So với Keno",
        "excerpt": "Bài mẫu về Mega 6/45. Trang Keno của chúng ta chưa có bài so sánh sản phẩm.",
        "word_count": 1100,
        "keyword_hints": "mega 6/45, keno khác mega",
        "schema_types": "Article",
        "published_hint": "2025-11-02",
        "status": "sample",
    },
    {
        "url": "https://example.com/mau/power-655",
        "product_hint": "power655",
        "title": "Power 6/55: cách chơi và lịch mở thưởng",
        "meta_description": "Nội dung Power 6/55 thường đứng cạnh Keno trên các hub xổ số.",
        "canonical": "https://example.com/mau/power-655",
        "headings": [
            {"tag": "h1", "text": "Power 6/55"},
            {"tag": "h2", "text": "Cơ cấu giải"},
            {"tag": "h2", "text": "Khác Keno"},
        ],
        "outline": "H1: Power 6/55\nH2: Cơ cấu giải\nH2: Khác Keno",
        "excerpt": "Bài mẫu Power 6/55 — gợi ý viết bài 'Keno và Power 6/55 khác nhau ở đâu'.",
        "word_count": 870,
        "keyword_hints": "power 6/55, xổ số vietlott",
        "schema_types": "Article, FAQPage",
        "published_hint": "2026-03-20",
        "status": "sample",
    },
    {
        "url": "https://example.com/mau/max-3d",
        "product_hint": "max3d",
        "title": "Max 3D và Max 3D Pro — người mới cần biết",
        "meta_description": "Sản phẩm 3D thường được tối ưu song song Keno trên blog xổ số.",
        "canonical": "https://example.com/mau/max-3d",
        "headings": [{"tag": "h1", "text": "Max 3D"}, {"tag": "h2", "text": "Cách dò vé"}],
        "outline": "H1: Max 3D\nH2: Cách dò vé",
        "excerpt": "Bài mẫu Max 3D. Gap: chưa có bài giải thích khác biệt với Keno.",
        "word_count": 540,
        "keyword_hints": "max 3d, dò vé",
        "schema_types": "Article",
        "published_hint": "2026-02-08",
        "status": "sample",
    },
]

SUGGESTED_GAP_TOPICS = [
    "Keno khác Mega 6/45 như thế nào?",
    "Keno và Power 6/55: tần suất mở thưởng",
    "Max 3D khác Keno ở điểm nào?",
    "Lotto 5/35 và Keno — chọn sản phẩm phù hợp",
    "Cách đọc bảng Lớn/Nhỏ Keno cho người mới",
    "Keno có bán online không?",
]
