# Generated by Django 5.2.17 on 2026-08-13 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokenLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=300, verbose_name='Trang nguồn')),
                ('target_url', models.CharField(max_length=500, verbose_name='Link')),
                ('status_code', models.PositiveSmallIntegerField(default=0, verbose_name='Mã HTTP')),
                ('is_internal', models.BooleanField(default=True, verbose_name='Nội bộ')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kiểm tra lúc')),
            ],
            options={
                'verbose_name': 'Link hỏng',
                'verbose_name_plural': 'Link hỏng',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='CoreWebVitalsNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày ghi')),
                ('lcp_note', models.CharField(blank=True, max_length=200, verbose_name='LCP (ghi chú tay)')),
                ('inp_note', models.CharField(blank=True, max_length=200, verbose_name='INP (ghi chú tay)')),
                ('cls_note', models.CharField(blank=True, max_length=200, verbose_name='CLS (ghi chú tay)')),
                ('notes', models.TextField(blank=True, default='- Ảnh bìa có width/height hoặc CSS cố định?\n- Font: preconnect Google Fonts?\n- Chart.js / Leaflet chỉ load trên trang cần?\n- Không đo Lighthouse tự động trên prototype này.', verbose_name='Checklist thủ công')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ghi chú Core Web Vitals',
                'verbose_name_plural': 'Ghi chú Core Web Vitals',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ResearchUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('product_hint', models.CharField(choices=[('keno', 'Keno'), ('power655', 'Power 6/55'), ('mega645', 'Mega 6/45'), ('max3d', 'Max 3D'), ('lotto535', 'Lotto 5/35'), ('other', 'Khác')], default='keno', max_length=20, verbose_name='Sản phẩm')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Tiêu đề')),
                ('meta_description', models.CharField(blank=True, max_length=400, verbose_name='Meta description')),
                ('canonical', models.CharField(blank=True, max_length=500, verbose_name='Canonical')),
                ('headings', models.JSONField(blank=True, default=list, verbose_name='Heading')),
                ('outline', models.TextField(blank=True, verbose_name='Dàn ý (heading)')),
                ('excerpt', models.TextField(blank=True, help_text='Tối đa ~400 ký tự phục vụ nghiên cứu — không lưu toàn văn.', verbose_name='Đoạn trích ngắn')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Số từ (ước tính)')),
                ('keyword_hints', models.CharField(blank=True, max_length=400, verbose_name='Gợi ý từ khóa')),
                ('schema_types', models.CharField(blank=True, max_length=200, verbose_name='Schema')),
                ('published_hint', models.CharField(blank=True, max_length=80, verbose_name='Ngày đăng (nếu có)')),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP')),
                ('robots_allowed', models.BooleanField(default=True, verbose_name='robots.txt cho phép')),
                ('status', models.CharField(choices=[('ok', 'Đã phân tích'), ('blocked', 'robots.txt chặn'), ('error', 'Lỗi / timeout'), ('sample', 'Mẫu minh họa')], default='ok', max_length=12, verbose_name='Trạng thái')),
                ('error_message', models.CharField(blank=True, max_length=300, verbose_name='Lỗi')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Phân tích lúc')),
            ],
            options={
                'verbose_name': 'URL thị trường',
                'verbose_name_plural': 'Nội dung thị trường',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='SeoRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_path', models.CharField(help_text='Ví dụ: /keno/ hoặc /bai-cu/', max_length=300, unique=True, verbose_name='Đường dẫn cũ')),
                ('to_path', models.CharField(help_text='Ví dụ: /huong-dan/ hoặc URL đầy đủ', max_length=300, verbose_name='Đường dẫn mới')),
                ('is_permanent', models.BooleanField(default=True, verbose_name='301 (vĩnh viễn)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Ghi chú')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='Lượt chuyển')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Redirect 301',
                'verbose_name_plural': 'Redirect 301',
                'ordering': ['from_path'],
            },
        ),
        migrations.CreateModel(
            name='SeoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitemap_generated_at', models.DateTimeField(blank=True, null=True)),
                ('linkcheck_at', models.DateTimeField(blank=True, null=True)),
                ('linkcheck_ok', models.PositiveIntegerField(default=0)),
                ('linkcheck_broken', models.PositiveIntegerField(default=0)),
                ('research_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Trạng thái công cụ SEO',
                'verbose_name_plural': 'Trạng thái công cụ SEO',
            },
        ),
    ]
