# Generated by Django 5.2.17 on 2026-08-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_article_seo_llm_and_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corewebvitalsnote',
            name='notes',
            field=models.TextField(blank=True, default='- Ảnh bìa có width/height hoặc CSS cố định?\n- Font: preconnect Google Fonts?\n- Chart.js / Leaflet chỉ load trên trang cần?', verbose_name='Checklist thủ công'),
        ),
        migrations.AlterField(
            model_name='researchurl',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Tối đa ~400 ký tự.', verbose_name='Đoạn trích ngắn'),
        ),
    ]
