# Generated by Django 5.2.17 on 2026-08-13 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GA4Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Ngày')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='Người dùng hoạt động')),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='Người dùng mới')),
                ('returning_users', models.PositiveIntegerField(default=0, verbose_name='Người dùng quay lại')),
                ('sessions', models.PositiveIntegerField(default=0, verbose_name='Phiên')),
                ('organic_sessions', models.PositiveIntegerField(default=0, verbose_name='Phiên organic')),
                ('referral_sessions', models.PositiveIntegerField(default=0, verbose_name='Phiên referral')),
                ('engaged_sessions', models.PositiveIntegerField(default=0, verbose_name='Phiên tương tác')),
                ('bounce_rate', models.FloatField(default=0, verbose_name='Tỷ lệ thoát (%)')),
                ('avg_session_duration', models.FloatField(default=0, verbose_name='Thời lượng phiên (s)')),
                ('pages_per_session', models.FloatField(default=0, verbose_name='Số trang / phiên')),
                ('d7_retention', models.FloatField(default=0, verbose_name='Giữ chân D7 (%)')),
                ('d30_retention', models.FloatField(default=0, verbose_name='Giữ chân D30 (%)')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Đồng bộ lúc')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload thô')),
            ],
            options={
                'verbose_name': 'GA4 snapshot',
                'verbose_name_plural': 'GA4 snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GSCSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Ngày')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Impressions')),
                ('ctr', models.FloatField(default=0, verbose_name='CTR (%)')),
                ('position', models.FloatField(default=0, verbose_name='Vị trí TB')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Đồng bộ lúc')),
            ],
            options={
                'verbose_name': 'Search Console snapshot',
                'verbose_name_plural': 'Search Console snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('result_view', 'Xem kết quả'), ('stats_view', 'Xem thống kê'), ('ticket_check', 'Dò vé'), ('simulator_play', 'Chơi thử'), ('find_pos_click', 'Nhấp Tìm điểm bán'), ('pos_search', 'Tìm kiếm điểm bán'), ('pos_detail', 'Xem chi tiết điểm bán'), ('get_directions', 'Nhấp Chỉ đường'), ('location_permission', 'Cấp quyền vị trí'), ('community_cta', 'CTA cộng đồng'), ('community_join_intent', 'Ý định tham gia nhóm'), ('voucher_issue', 'Nhận mã O2O')], db_index=True, max_length=48, verbose_name='Sự kiện')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Phiên')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='Đường dẫn')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Thời điểm')),
            ],
            options={
                'verbose_name': 'Sự kiện nội bộ',
                'verbose_name_plural': 'Sự kiện nội bộ',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_name', 'occurred_at'], name='analytics_a_event_n_aeeca0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Ngày')),
                ('source', models.CharField(choices=[('internal', 'Nội bộ'), ('ga4', 'Google Analytics 4'), ('gsc', 'Search Console')], max_length=16, verbose_name='Nguồn')),
                ('metric_name', models.CharField(db_index=True, max_length=64, verbose_name='Chỉ số')),
                ('value', models.FloatField(default=0, verbose_name='Giá trị')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Chi tiết')),
            ],
            options={
                'verbose_name': 'KPI hàng ngày',
                'verbose_name_plural': 'KPI hàng ngày',
                'ordering': ['-date', 'metric_name'],
                'unique_together': {('date', 'source', 'metric_name')},
            },
        ),
        migrations.CreateModel(
            name='GSCQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Ngày')),
                ('query', models.CharField(db_index=True, max_length=255, verbose_name='Từ khóa')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0, verbose_name='CTR (%)')),
                ('position', models.FloatField(default=0, verbose_name='Vị trí')),
                ('page', models.CharField(blank=True, max_length=400, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Từ khóa Search Console',
                'verbose_name_plural': 'Từ khóa Search Console',
                'ordering': ['-date', '-clicks'],
                'unique_together': {('date', 'query')},
            },
        ),
    ]
