# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityKpiSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(unique=True, verbose_name="Ngày")),
                ("new_members", models.PositiveIntegerField(default=0, verbose_name="Thành viên mới")),
                ("authentic_account_rate", models.FloatField(default=0, verbose_name="Tỷ lệ tài khoản xác thực (%)")),
                ("returning_active_pct", models.FloatField(default=0, verbose_name="Thành viên hoạt động quay lại (%)")),
                ("notes", models.CharField(blank=True, max_length=240, verbose_name="Ghi chú")),
            ],
            options={
                "verbose_name": "KPI cộng đồng (nhập tay)",
                "verbose_name_plural": "KPI cộng đồng (nhập tay)",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalKpiSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(unique=True, verbose_name="Ngày")),
                ("mobile_perf_score", models.FloatField(default=0, verbose_name="Điểm hiệu suất mobile")),
                ("lcp_ms", models.FloatField(default=0, verbose_name="LCP (ms)")),
                ("inp_ms", models.FloatField(default=0, verbose_name="INP (ms)")),
                ("cls", models.FloatField(default=0, verbose_name="CLS")),
                ("realtime_latency_ms", models.FloatField(default=0, verbose_name="Độ trễ realtime (ms)")),
                ("cwv_pass", models.BooleanField(default=False, verbose_name="Core Web Vitals đạt chuẩn")),
            ],
            options={
                "verbose_name": "KPI kỹ thuật",
                "verbose_name_plural": "KPI kỹ thuật",
                "ordering": ["-date"],
            },
        ),
    ]
