# Generated by Django 5.2.17 on 2026-08-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_community_technical_snapshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitykpisnapshot',
            options={'ordering': ['-date'], 'verbose_name': 'KPI cộng đồng', 'verbose_name_plural': 'KPI cộng đồng'},
        ),
    ]
