# Generated by Django 5.2.17 on 2026-08-13 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=80, unique=True, verbose_name='Từ khóa')),
                ('reason', models.CharField(blank=True, max_length=160, verbose_name='Lý do')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang lọc')),
            ],
            options={
                'verbose_name': 'Từ khóa cấm',
                'verbose_name_plural': 'Từ khóa cấm / anti-spam',
            },
        ),
        migrations.CreateModel(
            name='CommunityGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Tiêu đề')),
                ('body', models.TextField(verbose_name='Nội dung HTML')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
            ],
            options={
                'verbose_name': 'Nội quy cộng đồng',
                'verbose_name_plural': 'Nội quy cộng đồng',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Chủ đề')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('author_name', models.CharField(default='Ban quản trị', max_length=80, verbose_name='Người đăng')),
                ('pillar', models.CharField(choices=[('realtime', 'Keno Real-time'), ('knowledge', 'Keno Knowledge'), ('data', 'Keno Data'), ('community', 'Keno Community'), ('entertainment', 'Keno Entertainment')], default='community', max_length=24, verbose_name='Nhóm nội dung')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối / spam')], db_index=True, default='pending', max_length=16, verbose_name='Trạng thái')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật trên widget')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='Số bình luận (ước tính)')),
                ('rejection_reason', models.CharField(blank=True, max_length=200, verbose_name='Lý do từ chối')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Duyệt lúc')),
            ],
            options={
                'verbose_name': 'Bài thảo luận',
                'verbose_name_plural': 'Bài thảo luận cộng đồng',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JoinQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Câu hỏi lọc thành viên')),
                ('hint', models.CharField(blank=True, max_length=200, verbose_name='Gợi ý đáp án đúng')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
            ],
            options={
                'verbose_name': 'Câu hỏi lọc',
                'verbose_name_plural': 'Câu hỏi lọc thành viên',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MinigameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Tên hoạt động')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('scheduled_at', models.DateTimeField(verbose_name='Thời điểm')),
                ('reward_note', models.CharField(blank=True, help_text='Chỉ ghi nhận hoạt động cộng đồng đã được phê duyệt. Không cam kết trúng thưởng Keno.', max_length=160, verbose_name='Phần thưởng (nếu có)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Công khai')),
                ('participants', models.PositiveIntegerField(default=0, verbose_name='Lượt tham gia')),
            ],
            options={
                'verbose_name': 'Minigame / hoạt động',
                'verbose_name_plural': 'Minigame cộng đồng',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
