# Generated by Django 5.2.17 on 2026-08-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(max_length=80, unique=True, verbose_name='Facebook post ID')),
                ('message', models.TextField(blank=True, verbose_name='Nội dung')),
                ('created_time', models.DateTimeField(blank=True, null=True, verbose_name='Đăng lúc')),
                ('permalink', models.URLField(blank=True, max_length=500, verbose_name='Permalink')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đang công khai')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Đã ẩn')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Đồng bộ lúc')),
                ('last_api_error', models.CharField(blank=True, max_length=300, verbose_name='Lỗi API gần nhất')),
            ],
            options={
                'verbose_name': 'Bài Fanpage (cache)',
                'verbose_name_plural': 'Bài Fanpage (cache)',
                'ordering': ['-created_time', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='bannedkeyword',
            options={'verbose_name': 'Từ khóa cấm', 'verbose_name_plural': 'Từ khóa cấm'},
        ),
        migrations.AlterField(
            model_name='minigameevent',
            name='reward_note',
            field=models.CharField(blank=True, help_text='Không cam kết trúng thưởng.', max_length=160, verbose_name='Phần thưởng (nếu có)'),
        ),
    ]
